# Inserts a blank line between shell prompts
add_newline = false

# Time commands
command_timeout = 20000
scan_timeout = 10

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â¯](yellow)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
style = "119"
symbol = "ğŸ“¦"

[container]
format = '[$symbol \[$name\]]($style) '

# Python
[python]
symbol = "îˆµ "
style = "123"

# Directory
[directory]
truncation_length = 8
truncate_to_repo = false
style = "117"
read_only = " ï ½"
home_symbol = "~"

# Golang
[golang]
symbol = "î˜§ "
style = "189"

# Git Branch
[git_branch]
style = "9"

# Git Status
[git_status]
style = "117"
conflicted = "ğŸš©"
ahead = " Ahead "
behind = " Behind "
diverged = " ğŸ˜µ "
up_to_date = " Up to date "
untracked = ' [Untracked->$count](red) '
stashed = " [Stashed->$count] "
modified = ' [Modified->$count](yellow) '
staged = ' [Staged->$count](green) '
renamed = ' [Renamed->$count](blue) '
deleted = ' [Deleted->$count](bold red) '

[aws]
symbol = "â˜ï¸ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
disabled = false
format = "[ïŒˆ  $context](blue bold) "
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[java]
symbol = "î‰– "
style = "222"

[julia]
symbol = "î˜¤ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[perl]
symbol = "î© "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "

[lua]
format = "[î˜  ($version)](blue) "

[c]
style = "149"

[php]
format = '[ğŸ˜ $version](147 bold) '

