# Lithium

spacing         = 1
padding         = 0
hide_ascii      = true
separator       = "->"
key_color       = "Yellow"
separator_color = "Yellow"

[palette]
type            = "Light"
glyph           = "‚óè"
spacing         = 2
visible         = true

[bar]
glyph           = "‚óè"
symbol_open     = '['
symbol_close    = ''
visible         = true 
hide_delimiters = false

[box]
title           = " Settings ü§† "
border          = "double"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "Yellow"

[randomize]
key_color       = false
separator_color = false
pool            = "base"

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
gpu             = "GPU"
disk_space      = "Disk Space"
